routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/about','admin\AboutUsController@index');

// Form get
// Route::get('/form','admin\AboutUsController@show');

// Form post
// Route::post('/postformdata','admin\AboutUsController@postformdata');
// deleteitem
// Route::get('/deleteitem/{id}','admin\AboutUsController@delete');



//for update

//to get the data
// Route::get('/aboutedit/{id}','admin\AboutUsController@update');
// Route::post('/editformdata/{id}','admin\AboutUsController@updateformdata');

Route::get('/','admin\HomeController@index');
Route::resource('about', 'admin\AboutController');
Route::resource('product','admin\ProductController');
Route::resource('order','admin\OrderController');
Route::post('productSave','admin\ProductController@save');
Route::post('updateSave','admin\ProductController@aupdate');
Route::post('delete','admin\ProductController@delete');

resources/views/pages/about.blade.php
@extends('welcome')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
    <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below. For
        more
        information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official
            DataTables documentation</a>.</p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Heading</th>
                            <th>Description</th>
                            <th>Status</th>
                            <th>Updated date</th>
                            <th>Function</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($records as $record)
                        <tr>
                            <td> {{$record->id}} </td>
                            <td> {{$record->heading}} </td>
                            <td> {{$record -> description}} </td>
                            <td> {{$record -> status}} </td>
                            <td> {{$record->updated_date}} </td>
                            <td>
                                <a class="btn d-block btn-info mb-2"
                                    href="{{ route('about.edit',$record->id)}}">Edit</a>
                                <form action="{{route('about.destroy', $record->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn text-white btn-block btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
@endsection

resources/views/pages/addOrder.blade.php
@extends('welcome')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Order Listing Table</h1>
    <p class="mb-4">These all are Order available.</p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Order</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <button type="button" class="btn btn-info mb-3" data-toggle="modal" data-target="#addOrder">Add
                    Order</button>
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Updated Date</th>
                            <th>Function</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($orders as $order)
                        <tr>
                            <td> {{ $order-> id }} </td>
                            <td> {{ $order-> name }} </td>
                            <td> {{$order -> description}} </td>
                            <td> {{ $order -> updated_date }} </td>
                            <td>
                                <a class="btn btn-info text-capitalize btn-block" href="#">edit</a>
                                <a class="btn text-capitalize btn-danger btn-block" href="#">delete</a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- /.container-fluid -->
@endsection

<!-- Modal -->
{{-- Add Product --}}
<div class="modal fade" id="addOrder" tabindex="-1" role="dialog" aria-labelledby="addOrderTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add Order</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action=" {{ route('order.store') }} " id="form" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Enter order">
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <input type="text" name="description" class="form-control" id="description"
                            placeholder="Enter Description">
                    </div>
                    <div class="form-group">
                        <label for="updated_date">Updated Date</label>
                        <input type="date" name="updated_date" class="form-control" id="updated_date"
                            placeholder="Enter updated_date">
                    </div>
                    <button type="submit" class="btn btn-info mb-3">Add Product!!</button>
                    <button type="submit" class="btn btn-danger mb-3" data-dismiss="modal">Cancel Product!!</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/pages/editform.blade.php
@extends('welcome')
@section('content')
<div class="container my-4">
    <div class="row">
        <div class="col-12">
            <h1>Edit Form</h1>
        </div>
        <!-- Update -->
        <div class="col-7">

            <form action="{{route('about.update',$rec->id)}}" method="POST" role="form" enctype="multipart/form-data" >
                @csrf
                @method('put')
                <div class="form-group">
                    <label for="heading">Heading:</label>
                    <input name="heading" type="text" class="form-control" placeholder="Enter Heading" id="heading"
                        value="{{$rec->heading}}">
                </div>
                <div class="form-group">
                    <label for="description">Description:</label>
                    <textarea name="description" type="text" rows="5" class="form-control"
                        placeholder="Enter Description" id="description">{{$rec->description}}</textarea>
                </div>
                <label>Status:</label>
                <div class="form-group">
                    <label for="date">Updated date:</label>
                    <input name="date" type="date" class="form-control" placeholder="Enter Date" id="date"
                        value="{{$rec->updated_date}}">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/pages/editproduct.blade.php
@extends('welcome')
@section('content')
<div class="container my-4">
    <div class="row">
        <div class="col-12">
            <h1>Edit Product</h1>
        </div>
        <!-- Update -->
        <div class="col-7">
            <form method="POST" action="{{route('product.update', $editproduct -> id)}}" id="form"
                enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name</label>
                    <input value="{{$editproduct->name}}" type="text" name="name" class="form-control" id="name"
                        placeholder="Enter product">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <input value="{{$editproduct->description}}" type="text" name="description" class="form-control"
                        id="description" placeholder="Enter Description">
                </div>
                <div class="form-group">
                    <label for="updated_date">Updated Date</label>
                    <input type="date" value="{{ $editproduct -> updated_date }}" name="updated_date"
                        class="form-control" id="updated_date" placeholder="Enter updated_date">
                </div>
                <div class="form-group">
                    <label for="image">Edit Image</label>
                    <input type="file" name="image" value="{{ $editproduct->image }}" id="image">
                </div>
                <button type="submit" class="btn btn-info mb-3">Edit Product!!</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/pages/form.blade.php
@extends('welcome')
@section('content')
<div class="container my-4">
    <div class="row">
        <div class="col-12">
            <h1>Add About</h1>
        </div>
        <!-- Insert -->
        <div class="col-7">
            <form action=" {{route('about.store')}} " role="form" enctype="multipart/form-data" method="POST">
                @csrf
                <div class="form-group">
                    <label for="heading">Heading:</label>
                    <input name="heading" type="text" class="form-control" placeholder="Enter Heading" id="heading">
                </div>
                <div class="form-group">
                    <label for="description">Description:</label>
                    <textarea name="description" type="text" rows="5" class="form-control"
                        placeholder="Enter Description" id="description"></textarea>
                </div>
                <label>Status:</label>
                <div class="form-check">
                    <input type="radio" name="status" value="0" class="form-check-input" id="zero">
                    <label class="form-check-label" for="zero">0</label>
                </div>
                <div class="form-check">
                    <input type="radio" name="status" value="1" class="form-check-input" id="one">
                    <label class="form-check-label" for="one">1</label>
                </div>
                <div class="form-group">
                    <label for="date">Updated date:</label>
                    <input name="date" type="date" class="form-control" placeholder="Enter Date" id="date">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/pages/product.blade.php
@extends('welcome')
@section('content')
<!-- Begin Page Content -->

<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Product Listing Table</h1>
    <p class="mb-4">These all are products available.</p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Products</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-info mb-3" id="showaddModal" data-toggle="modal"
                    data-target="#addProducts">
                    Add Products
                </button>
                <div class="modal fade" id="addProducts" tabindex="-1" role="dialog"
                    aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="modalTitle"></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            @csrf
                            <div class="modal-body">
                                <input type="hidden" id="modalId" />
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" name="name" class="form-control" id="name"
                                        placeholder="Enter product">
                                </div>
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <input type="text" name="description" class="form-control" id="description"
                                        placeholder="Enter Description">
                                </div>
                                <div class="form-group">
                                    <label for="updated_date">Updated Date</label>
                                    <input type="date" name="updated_date" class="form-control" id="updated_date"
                                        placeholder="Enter Date">
                                </div>
                                <button type="submit" id="addProductButton" data-dismiss="modal"
                                    class="btn btn-info mb-3">Add Product</button>
                                <button type="submit" data-dismiss="modal" id="editProductButton" class="btn btn-info mb-3">Edit
                                    Product</button>
                                <button type="submit" id="deleteProductButton" class="btn btn-info mb-3">Delete
                                    Product</button>
                                <button type="submit" data-dismiss="modal" id="saveProductButton" class="btn btn-info mb-3">Save
                                    Product</button>
                                <button class="btn btn-danger mb-3" data-dismiss="modal">Cancel
                                    Product!!</button>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Updated Date</th>
                            <th>Function</th>
                        </tr>
                    </thead>
                    <tbody id="tbody">
                        @foreach ($products as $p)
                        <tr id="tr">
                            <input id="getId" type="hidden" value={{ $p->id }} />
                            <td> {{ $p->id }} </td>
                            <td> {{ $p->name }} </td>
                            <td> {{ $p->description }} </td>
                            <td> {{ $p->updated_date }} </td>
                            <td>
                                <a id="editProductButton" data-toggle="modal" data-target="#addProducts"
                                    class="btn btn-info mb-3 text-white btn-block">Edit</a>
                                <button id="deleteProductButton" class="btn btn-danger btn-block">Delete</button>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>


<!-- /.container-fluid -->
@endsection



{{-- <div class="modal fade" id="editProduct" tabindex="-1" role="dialog" aria-labelledby="editProductTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Edit Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{route('product.update', $editproduct->id)}}" id="form"
enctype="multipart/form-data">
@csrf
@method('PUT')
<div class="form-group">
    <label for="name">Name</label>
    <input value="{{$product->name}}" type="text" name="name" class="form-control" id="name"
        placeholder="Enter product">
</div>
<div class="form-group">
    <label for="description">Description</label>
    <input value="{{$editproduct->description}}" type="text" name="description" class="form-control" id="description"
        placeholder="Enter Description">
</div>
<div class="form-group">
    <label for="updated_date">Updated Date</label>
    <input type="date" name="updated_date" class="form-control" id="updated_date" placeholder="Enter updated_date">
</div>
<button type="submit" class="btn btn-info mb-3">Edit Product!!</button>
<button type="submit" class="btn btn-danger mb-3" data-dismiss="modal">Cancel Product!!</button>
</form>

</div>
</div>
</div>
</div> --}}